name: custom-greetings
on:
  push:
    branches: [Himel]

jobs:
  greetings:
    name: custom-greetings
    runs-on: ubuntu-latest
  steps:
    - name: First step
      run: echo "hello world"