name: custom-greeting-nodejs

on:
  push:
    branches: [Himel]

jobs:
  nodesjsApply:
    runs-on: ubuntu-latest
    name: test nodejs
    steps:
      - name: install node js
      - uses: actions/setup-node@v6
        with:
          node-version: '18'
      - run: node -v
      - name: checking npm 
      - run: npm version

